[package]
name = "ring-buffer"
version = "0.1.0"
edition = "2021"

[lib]
name = "ring_buffer"
crate_type = ["cdylib"]


[dependencies]
arrayvec = "0.7.2"
pyo3 = {version = "0.19.0", features = ["extension-module"]}

[build-dependencies]
maturin = "1.0.1"