[build-system]
requires = ["setuptools", "wheel", "maturin"]
build-backend = "maturin"


[project]
name = "ukf"
version = "0.0.1"
dependencies = ["numpy", "filterpy", "matplotlib", "wheel", "maturin"]

[project.optional-dependencies]
dev = ["pytest", "black", "ruff", "jupyter", "mypy"]
